version: '3'

services:
  apache-php:
    build:
       ./php
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7.34
    volumes:
      - ./mysql/DB:/var/www/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: first_tasks
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - DB_HOST=mysql
      - DB_USERNAME=root
