version: '3'

services:
  apache-php:
    build:
       ./php
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/test_db.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: first_tasks

  phpmyadmin:
    image: phpmyadmin
    restart: always
    volumes:
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=firsttask_mysql_1
      - PMA_USER=root
      - PMA_PASSWORD=root
      - DB_HOST=mysql
      - DB_USERNAME=root
